### ISSUE TITLE
Switch CMS to a more popular choice

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#56]
- Netlify CMS (now Decap CMS) is basically dead at this point. Support server is extremely inactive, and a lot of missing features are in the product.

https://jamstack.org/survey/2022/#content-management-systems

We should switch the CMS to probably Strapi or Sanity, depending on if we can get around the 3-user limit on Sanity.

**Comment by WhiteHoodHacker** [comment]
Strapi and Sanity both store content in their own databases, not git. Unless we want to change the fundamental model that the website operates on (which is all content is stored in the content folder in the repo), then this is a problem. The CMS was intended to be an optional subsystem to the site. By using one of these services, we now create a dependence on their API in order to build the site (and we lose "ownership" of our content).

I chose Netlify CMS because it was the only git-based CMS I could find that provided content type customization and didn't request full permissions to a user's GitHub account (which was my main issue with prose.io).

**Comment by reteps** [comment]
Ok, that makes sense.

**Comment by WhiteHoodHacker** [comment]
That being said, Prose is probably one of the more popular git-based CMS and we could create our own self-hosted Prose instance if we ever wanted to ditch Netlify CMS.
