### ISSUE TITLE
Add CVE content type / alternate strategy

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#80]
- Add a page displaying all CVEs the club has found. Currently the CVE model doesn't fit well into the publication schema, since it has no image.

**Comment by WhiteHoodHacker** [comment]
I don't think this is needed, mainly because I don't believe we should simply list CVEs that the club has found. Usually, when we share a CVE, we would share either a write-up of the CVE or a news article/blog post: all of which images can be generated for. Images don't also have to be serious or depict the CVE - they can be relevant memes too.

An alternative solution to requiring images is to simply display a shortened version of the post title in lieu of an image: in this case, it could just be the CVE number. But this would be an enhancement that applies to all publications and doesn't warrant creating a separate CVE content type.
