### ISSUE TITLE
Update meeting schema

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#87]
Improve meeting schema with two fields:

- `linked_category` - The category on CTFd the meeting challenges are linked to
- `linked_challenges` - A list of linked challenge IDs the meeting is tied to (this shouldn't be manually edited except for in rare cases).

This will allow us to have a GitHub action that sets the linked category when it is created on CTFd, and link a list of challenges when the year is over.

**Comment by WhiteHoodHacker** [comment]
I do still have some concerns with this - namely that we'd have a single GitHub Action that someone would have to remember to run at the end of the year - if they don't and the categories reset the following year, the correctly linked challenges are gone. Linking a category by name is also a lot less certain of a format where a date is a standardized format and immediately traceable to a meeting.

To me, it is far simpler to use the date. It allows the meeting to know what challenges to fetch because it knows its own date to fetch challenges tagged with that date. It works the same the other way around - a challenge has the dates in its tags which can be used to create a URL to the correct meeting page. It also creates zero dependencies between CTFd and sigpwny.com. In order for your proposed method to work, the CTFd would need to know the sigpwny.com meeting URL and the sigpwny.com site would need to be updated with the correct category name. If the category name changes on CTFd for whatever reason, the sigpwny.com meeting needs to be updated. This would not be an issue with date tags, since there is no reason for them to be updated or removed.

**Comment by reteps** [comment]
This all needs to happen in 2 steps for me to be happy. I do not want anyone to manually tag meetings with a date, it should be as frictionless on top of CTFd as possible. 

I would be OK with when the CTFd category is linked to a meeting, it pulls all challenges in that category and puts them on the website. You could even add a "resync" button if you need to add more later.

I am pretty firmly against individual tagging.

**Comment by WhiteHoodHacker** [comment]
We ended up going with a strategy similar to what I was suggesting via a /dates endpoint, so this is wontfix
